Added Docs For Maps
Calamity210/BirbLang pull request #43
Opened 2020-09-12 07:53 UTC by Andy-Python-Programmer

Added Docs For Maps

Extends: #33

2020-09-12 11:17 UTC, Calamity210 requested changes

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +A collection of key/value pairs, from which you retrieve a value using its associated key.
Lets be more original rather than taking it from darts docs

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +screm(map);
`screm(map['content']);` is preferred

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +## isEmpty
Make this h3

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +True if this String is not empty.
Its a map, not a string

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +True is this String is empty
Its a map, not string

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +Returns an int containing the length of this String.
Again, it isnt a string

2020-09-12 11:17 UTC, Calamity210 commented on docs/docs/Core/map.md
> +### hashCode
Remove the hashcode section

2020-09-13 02:58 UTC, Calamity210 requested changes

2020-09-13 02:58 UTC, Calamity210 commented on docs/docs/Core/map.md
> +True is this Map is empty
Typo: if

2020-09-13 02:58 UTC, Calamity210 commented on docs/docs/Core/map.md
> +`String string`
Should be `String toString`

2020-09-13 02:58 UTC, Calamity210 commented on docs/docs/Core/map.md
> +True if this Map is not empty.
Specify that it returns a bool for consistency. `Returns a bool that is true if this Map is not empty.` do the same for isEmpty pls

2020-09-13 03:09 UTC, Calamity210 approved these changes
LGTM

2020-09-13 03:09 UTC, merged

2020-09-13 03:09 UTC, Andy-Python-Programmer commented
Merged!