OS
Calamity210/BirbLang pull request #45
Opened 2020-09-12 10:37 UTC by Andy-Python-Programmer

Added os commands
1. system (perform a system operation)
2. cwd (get the cwd())

2020-09-12 10:43 UTC, Andy-Python-Programmer commented
@AkramIzz Note the test will fail as its you know a ci and where dart even in cmd will not work

2020-09-12 11:03 UTC, Andy-Python-Programmer commented
Test are failing as of echo :(

2020-09-12 11:21 UTC, Calamity210 requested changes

2020-09-12 11:21 UTC, Calamity210 commented on lib/external/io.dart
> +  Directory current = Directory.current;
This line is redundant. If current is only used once, i wouldn't say its worth making a separate variable for it. Use Directory.current directly

2020-09-12 11:21 UTC, Calamity210 commented on lib/external/io.dart
> +  res.stringValue = current.path.toString();
Return the absolute path

2020-09-12 11:21 UTC, Calamity210 commented on lib/external/io.dart
> +  registerGlobalFunction(runtime, 'cwd', funcCwd);
This would be better to be registered as a variable than a function

2020-09-13 01:28 UTC, Andy-Python-Programmer commented on lib/external/io.dart
> +      .then((ProcessResult pr) {
Done!

2020-09-13 01:59 UTC, Andy-Python-Programmer commented
The os is destoryed as of git. Git is stressfull

2020-09-13 01:59 UTC, closed without merging