Added No Seeb Operators
Calamity210/BirbLang pull request #54
Opened 2020-09-19 03:39 UTC by Andy-Python-Programmer

Added No Seeb Operators

2020-09-19 03:52 UTC, Calamity210 requested changes

2020-09-19 03:52 UTC, Calamity210 commented on lib/runtime/runtime.dart
> +        else{
Else clause is not needed due to the `return`

2020-09-19 03:52 UTC, Calamity210 commented on lib/runtime/runtime.dart
> +        if (left.type == ASTType.AST_NULL){
Prefer `left is NullNode`

2020-09-19 03:55 UTC, Andy-Python-Programmer commented on lib/runtime/runtime.dart
> +        if (left.type == ASTType.AST_NULL){
Ah. I see. I will do it :)

2020-09-21 05:13 UTC, Calamity210 requested changes

2020-09-21 05:13 UTC, Calamity210 commented on lib/runtime/runtime.dart
> +              return astVarDef.variableValue = value;
Be sure to use cascades. ```
 return astVarDef..variableValue = value;
```

2020-09-21 05:13 UTC, Calamity210 commented on lib/runtime/runtime.dart
> +            return value;
Why are you returning value here? It should be astVarDef

2020-09-21 05:38 UTC, Calamity210 approved these changes

2020-09-21 05:38 UTC, merged