Website Updates
Calamity210/BirbLang pull request #66
Opened 2020-09-28 03:28 UTC by Andy-Python-Programmer

Website Updates

2020-09-28 03:34 UTC, Calamity210 requested changes

2020-09-28 03:34 UTC, Calamity210 commented on docs/src/pages/index.js
> +                  <p>Eaay to make apps in less amount of code and pretty easy to learn if you know any other language</p>
Easy to make apps?

2020-09-28 03:34 UTC, Calamity210 commented on docs/src/pages/index.js
> +                  <h2>Null Saftey</h2>
It would be spelled safety

2020-09-28 03:34 UTC, Calamity210 commented on docs/src/pages/index.js
> +                  <p>Avoid entire classes of errors such as null pointer exceptions</p>
You wouldnt encounter a null pointer in dart nor in birb regardless, and null safety isnt really ready so I wouldn't put this up yet

2020-09-28 03:34 UTC, Calamity210 commented on docs/src/pages/index.js
> +                      <p>Install Birb Code VS Code extention from VS Code Marketplace</p>
Extension

2020-09-28 03:34 UTC, Calamity210 commented on docs/src/pages/index.js
> +            <h1 align="center">Try Birb in your browser</h1>
Repeated phrase, try rephrasing it

2020-10-07 14:14 UTC, Calamity210 commented
@Andy-Python-Programmer can you provide a preview of what the changes actually look like?

2020-10-08 00:14 UTC, Andy-Python-Programmer commented
![EC414DA6-2B52-4049-9409-A077067353EB-1436-000001ACFA0A62C5](https://user-images.githubusercontent.com/62820092/95400764-3622ff00-0957-11eb-8d78-25aaf118c801.jpeg)
![F838787E-D868-4B78-B9B7-01E741C5FA47-1436-000001ACFE73A60F](https://user-images.githubusercontent.com/62820092/95400741-21df0200-0957-11eb-8332-5297bc070731.jpeg)

@Calamity210 The image is a bit blurry as I just pulled them from Discord. But this is exact design how they will look.

2020-10-08 01:15 UTC, Calamity210 requested changes

2020-10-08 01:15 UTC, Calamity210 commented on docs/src/pages/index.js
> +                      <p>Try Birb in your browser! All of the Birb core libs are included</p>
Prefer to not use abbreviations

2020-10-08 01:15 UTC, Calamity210 commented on docs/src/pages/index.js
> +                      <p>Use the interactive Birb shell in your terminal / bash</p>
/ bash is not needed

2020-10-08 01:15 UTC, Calamity210 commented on docs/src/pages/index.js
> +            <iframe src="https://play-birbolang.web.app/#/" width="95%" height="500px" scrolling="yes" align="center"></iframe>
Can you center this horizontally?

2020-10-08 02:26 UTC, Andy-Python-Programmer commented on docs/src/pages/index.js
> +                      <p>Use the interactive Birb shell in your terminal / bash</p>
Yeup

2023-08-19 05:41 UTC, closed without merging